/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aulasete;

/**
 *
 * @author lucas
 */
public class OperadoresSwing extends javax.swing.JFrame {

    /**
     * Creates new form OperadoresSwing
     */
    public OperadoresSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCacl = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNumUm = new javax.swing.JTextField();
        txtNumDois = new javax.swing.JTextField();
        lblNum1Soma = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNum2Soma = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        resultSoma = new javax.swing.JLabel();
        lblNum2Sub = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        resultSub = new javax.swing.JLabel();
        lblNum1Sub = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNum2Mult = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        resultMult = new javax.swing.JLabel();
        lblNum1Mult = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNum1Div = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNum2Div = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        resultDiv = new javax.swing.JLabel();
        lblNum1Res = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblNum2Res = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        resultRes = new javax.swing.JLabel();
        lblNum1DivF = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblNum2DivF = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        resultDivF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("1º Número:");

        btnCacl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCacl.setText("Calcular");
        btnCacl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaclActionPerformed(evt);
            }
        });

        jLabel2.setText("2º Número:");

        txtNumUm.setText("0");

        txtNumDois.setText("0");

        lblNum1Soma.setText("0");

        jLabel4.setText("+");

        lblNum2Soma.setText("0");

        jLabel6.setText("=");

        resultSoma.setText("0");

        lblNum2Sub.setText("0");

        jLabel7.setText("=");

        resultSub.setText("0");

        lblNum1Sub.setText("0");

        jLabel5.setText("-");

        lblNum2Mult.setText("0");

        jLabel8.setText("=");

        resultMult.setText("0");

        lblNum1Mult.setText("0");

        jLabel9.setText("*");

        lblNum1Div.setText("0");

        jLabel10.setText("/");

        lblNum2Div.setText("0");

        jLabel11.setText("(Quociente)   =");

        resultDiv.setText("0");

        lblNum1Res.setText("0");

        jLabel12.setText("%");

        lblNum2Res.setText("0");

        jLabel13.setText("(Resto)   =");

        resultRes.setText("0");

        lblNum1DivF.setText("0");

        jLabel14.setText("/");

        lblNum2DivF.setText("0");

        jLabel15.setText("(Divisão números reais)   =");

        resultDivF.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNum1Sub)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(22, 22, 22)
                            .addComponent(lblNum2Sub, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNum1Soma)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(lblNum2Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNum1Div)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNum1Res)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNum1Mult)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNum1DivF)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNum2Mult, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNum2Res, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNum2Div, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNum2DivF, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultSub)
                            .addComponent(resultSoma)
                            .addComponent(resultMult)
                            .addComponent(resultDiv)
                            .addComponent(resultRes)
                            .addComponent(resultDivF)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumUm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumDois, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCacl)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtNumUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCacl)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum1Soma)
                    .addComponent(jLabel4)
                    .addComponent(lblNum2Soma)
                    .addComponent(jLabel6)
                    .addComponent(resultSoma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum1Sub)
                    .addComponent(jLabel5)
                    .addComponent(lblNum2Sub)
                    .addComponent(jLabel7)
                    .addComponent(resultSub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum1Mult)
                    .addComponent(jLabel9)
                    .addComponent(lblNum2Mult)
                    .addComponent(jLabel8)
                    .addComponent(resultMult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum1Div)
                    .addComponent(jLabel10)
                    .addComponent(lblNum2Div)
                    .addComponent(jLabel11)
                    .addComponent(resultDiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum1Res)
                    .addComponent(jLabel12)
                    .addComponent(lblNum2Res)
                    .addComponent(jLabel13)
                    .addComponent(resultRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum1DivF)
                    .addComponent(jLabel14)
                    .addComponent(lblNum2DivF)
                    .addComponent(jLabel15)
                    .addComponent(resultDivF))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaclActionPerformed
        int n1,n2;
        // Transformar textos em inteiros para cálculos
        n1 = Integer.parseInt(txtNumUm.getText());
        n2 = Integer.parseInt(txtNumDois.getText());
        // Adição
        lblNum1Soma.setText(Integer.toString(n1));
        lblNum2Soma.setText(Integer.toString(n2));
        resultSoma.setText(Integer.toString((n1+n2)));
        // Subtração
        lblNum1Sub.setText(Integer.toString(n1));
        lblNum2Sub.setText(Integer.toString(n2));
        resultSub.setText(Integer.toString((n1-n2)));
        // Multiplicação
        lblNum1Mult.setText(Integer.toString(n1));
        lblNum2Mult.setText(Integer.toString(n2));
        resultMult.setText(Integer.toString((n1*n2)));
        // Divisao Quociente Inteira
        lblNum1Div.setText(Integer.toString(n1));
        lblNum2Div.setText(Integer.toString(n2));
        resultDiv.setText(Integer.toString((n1/n2)));
        // Divisao Quociente Inteira
        lblNum1Res.setText(Integer.toString(n1));
        lblNum2Res.setText(Integer.toString(n2));
        resultRes.setText(Integer.toString((n1%n2)));
        // Divisao Float
        float n1f = (float) n1;
        float n2f = (float) n2;
        lblNum1DivF.setText(Float.toString(n1f));
        lblNum2DivF.setText(Float.toString(n2f));
        resultDivF.setText(Float.toString((n1f/n2f)));
    }//GEN-LAST:event_btnCaclActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperadoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperadoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperadoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperadoresSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperadoresSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCacl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNum1Div;
    private javax.swing.JLabel lblNum1DivF;
    private javax.swing.JLabel lblNum1Mult;
    private javax.swing.JLabel lblNum1Res;
    private javax.swing.JLabel lblNum1Soma;
    private javax.swing.JLabel lblNum1Sub;
    private javax.swing.JLabel lblNum2Div;
    private javax.swing.JLabel lblNum2DivF;
    private javax.swing.JLabel lblNum2Mult;
    private javax.swing.JLabel lblNum2Res;
    private javax.swing.JLabel lblNum2Soma;
    private javax.swing.JLabel lblNum2Sub;
    private javax.swing.JLabel resultDiv;
    private javax.swing.JLabel resultDivF;
    private javax.swing.JLabel resultMult;
    private javax.swing.JLabel resultRes;
    private javax.swing.JLabel resultSoma;
    private javax.swing.JLabel resultSub;
    private javax.swing.JTextField txtNumDois;
    private javax.swing.JTextField txtNumUm;
    // End of variables declaration//GEN-END:variables
}
