/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import java.time.Year;

/**
 *
 * @author lucas
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        //Inicia alguns botões sem visibilidade para o usuário e inicia o campo do ano atual.
        String ano = Year.now().toString();
        anoAtual.setText(ano);
        lblIdade.setVisible(false);
        idade.setVisible(false);
        votoObrig.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        anoNasc = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        anoAtual = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        idade = new javax.swing.JLabel();
        calcularIdade = new javax.swing.JButton();
        votoObrig = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 420));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Digite o ano de Nascimento:");

        anoNasc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Ano atual:");

        anoAtual.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        anoAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anoAtual.setText("0");

        lblIdade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblIdade.setText("Idade:");

        idade.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        idade.setForeground(new java.awt.Color(204, 0, 0));
        idade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idade.setText("0");

        calcularIdade.setBackground(new java.awt.Color(51, 51, 51));
        calcularIdade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        calcularIdade.setForeground(new java.awt.Color(153, 255, 204));
        calcularIdade.setText("Calcular Idade");
        calcularIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularIdadeActionPerformed(evt);
            }
        });

        votoObrig.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        votoObrig.setText("txtInvisib");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(votoObrig)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(calcularIdade))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblIdade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(56, 56, 56)
                            .addComponent(anoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(anoNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(anoAtual))
                .addGap(48, 48, 48)
                .addComponent(calcularIdade)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdade)
                    .addComponent(idade))
                .addGap(33, 33, 33)
                .addComponent(votoObrig)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularIdadeActionPerformed
        // TODO add your handling code here:
        //Calcula e retorna a idade, tornando essas informações visiveis ao usuário
        int anoNascI, anoAtualI, idadeI;
        anoNascI = Integer.parseInt(anoNasc.getValue().toString());
        anoAtualI = Integer.parseInt(anoAtual.getText());
        idadeI = anoAtualI - anoNascI;
        idade.setText(Integer.toString(idadeI));
        idade.setVisible(true);
        lblIdade.setVisible(true);
        //Condicional para retornar se voto é obrigatório ou não conforme faixa etária.
        if (idadeI < 0){
            votoObrig.setText("<html>O ano de nascimento não pode ser posterior ao ano atual.</html>");
            votoObrig.setVisible(true);
        }
        else if ((idadeI >= 0) & (idadeI < 16)){
            votoObrig.setText("<html>Para a sua idade o voto é: <strong>Proibido</strong>.</html>");
            votoObrig.setVisible(true);
        }
        else if (((idadeI >= 16) & (idadeI < 18)) | (idadeI > 70) & (idadeI < 1000)){
            votoObrig.setText("<html>Para a sua idade o voto é: <strong>Opcional</strong>.</html>");
            votoObrig.setVisible(true);
        }
        else if ((idadeI >= 18) & (idadeI <= 70)){
            votoObrig.setText("<html>Para a sua idade o voto é: <strong>Obrigatório</strong>.</html>");
            votoObrig.setVisible(true);
        }
        else if (idadeI > 1000){
            votoObrig.setText("<html>É impossível <strong>Kakaroto</strong>, sua idade é mais de 1000!");
            votoObrig.setVisible(true);
        }
        else
            votoObrig.setText("ERRO: valor inválido tente novamente.");
            votoObrig.setVisible(true);
    }//GEN-LAST:event_calcularIdadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoAtual;
    private javax.swing.JSpinner anoNasc;
    private javax.swing.JButton calcularIdade;
    private javax.swing.JLabel idade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel votoObrig;
    // End of variables declaration//GEN-END:variables
}
