/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula14exercicios;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author lucas
 */
public class Aula14VetorEx extends javax.swing.JFrame {

    /**
     * Creates new form Aula14VetorEx
     */
    int vetor[] = new int[5];
    DefaultListModel list = new DefaultListModel();
    int selecionado = 0;
    
    
    public Aula14VetorEx() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valor = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        botaoAd = new javax.swing.JButton();
        botaoRm = new javax.swing.JButton();
        botaoOr = new javax.swing.JButton();
        posList = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        valor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Vetor");

        lista.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lista.setModel(list);
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        botaoAd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botaoAd.setText("Adicionar");
        botaoAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdActionPerformed(evt);
            }
        });

        botaoRm.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botaoRm.setText("Remover");
        botaoRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRmActionPerformed(evt);
            }
        });

        botaoOr.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botaoOr.setText("Ordenar");
        botaoOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOrActionPerformed(evt);
            }
        });

        posList.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        posList.setText("[-]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoOr)
                    .addComponent(botaoAd)
                    .addComponent(botaoRm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(posList, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoAd)
                        .addGap(18, 18, 18)
                        .addComponent(botaoRm)
                        .addGap(18, 18, 18)
                        .addComponent(botaoOr))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(posList))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        // TODO add your handling code here:
        selecionado = lista.getSelectedIndex();
        posList.setText("[" + selecionado + "]");
    }//GEN-LAST:event_listaMouseClicked

    private void botaoAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdActionPerformed
        // TODO add your handling code here:
        vetor[selecionado] = Integer.parseInt(valor.getValue().toString());
        list.removeAllElements();
        for(int i = 0; i < vetor.length; i++)
            list.addElement(vetor[i]);
    }//GEN-LAST:event_botaoAdActionPerformed

    private void botaoRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRmActionPerformed
        // TODO add your handling code here:
        vetor[selecionado] = 0;
        list.removeAllElements();
        for(int i = 0; i < vetor.length; i++)
            list.addElement(vetor[i]);
    }//GEN-LAST:event_botaoRmActionPerformed

    private void botaoOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOrActionPerformed
        // TODO add your handling code here:
        Arrays.sort(vetor);
        list.removeAllElements();
        for (int i = 0; i < vetor.length; i++)
            list.addElement(vetor[i]);
    }//GEN-LAST:event_botaoOrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aula14VetorEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aula14VetorEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aula14VetorEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aula14VetorEx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aula14VetorEx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAd;
    private javax.swing.JButton botaoOr;
    private javax.swing.JButton botaoRm;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista;
    private javax.swing.JLabel posList;
    private javax.swing.JSpinner valor;
    // End of variables declaration//GEN-END:variables
}
